In [5]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('filtered_final_merged_file.csv')

# Filter columns that contain 'credit' in their names and drop them
columns_to_drop = [col for col in df.columns if 'credit' in col]
df.drop(columns=columns_to_drop, inplace=True)

# Save the modified DataFrame back to a CSV file
df.to_csv('filtered_final_merged_file.csv(without_credit)', index=False)
df

,IT_Experience,MAT 151-grade,MAT 153-grade,INF 106-grade,MAT 156-grade,CSS 215-grade,MAT 251-grade,CSS 220-grade,CSS 410-grade,MDE 171/HSS 111-grade,...,MDE 141/HSS 195-grade,MDE 142/HSS 196-grade,MDE 132/TUR 102-grade,CSS 312/INF 313-grade,MDE 143/HSS 295-grade,CSS 206/INF 202-grade,MDE 144/HSS 296-grade,MDE 134/TUR 214-grade,MAT 158/MAT 154-grade,HSS 222/MDE 172-grade
0,Android,71.0,75,71,61.0,77,78,75.0,97.0,92,...,98,91,58.0,70.0,93.0,83.0,92,74,63.0,77.0
1,IT Project Manager,80.0,90,92,85.0,53,52,66.0,95.0,90,...,95,91,64.0,63.0,94.0,65.0,92,70,75.0,57.0
2,Front End Developer,90.0,95,91,90.0,96,87,71.0,93.0,86,...,97,92,75.0,92.0,91.0,78.0,93,65,90.0,80.0
3,Front End Developer,90.0,84,86,90.0,84,87,55.0,100.0,90,...,100,91,75.0,62.0,94.0,73.0,92,50,82.0,62
4,IT project manager,90.0,93,96,85.0,75,80,70.0,NaN,96,...,95,93,84.0,82.0,91.0,73.0,93,66,93.0,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,UX/UI Designer,50.0,81.0,50.0,56.0,78.0,63.0,50.0,54.0,71.0,...,84.0,95.0,NaN,0.0,90.0,NaN,95.0,NaN,0.0,88.0
197,Data Science,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,85.0,...,95.0,95.0,NaN,80.0,100.0,94.0,87.0,NaN,73.0,95.0
198,ICT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.0,...,93.0,95.0,95.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,Backend developer,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,85.0,...,95.0,95.0,NaN,80.0,100.0,94.0,87.0,NaN,73.0,95.0
200,Unity developer,68.0,53.0,70.0,60.0,59.0,68.0,74.0,NaN,81.0,...,95.0,100.0,64.0,0.0,90.0,86.0,95.0,83.0,62.0,59.0

In [29]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('filtered_final_merged_file.csv(without_credit)')

# Count NaN values in each row
nan_count = df.isna().sum(axis=1)

# Drop rows with more than 5 NaN values
df = df[nan_count <= 5]

# Save the modified DataFrame back to a CSV file
df.to_csv('modified_file05.csv', index=False)
df

,IT_Experience,MAT 151-grade,MAT 153-grade,INF 106-grade,MAT 156-grade,CSS 215-grade,MAT 251-grade,CSS 220-grade,CSS 410-grade,MDE 171/HSS 111-grade,...,MDE 141/HSS 195-grade,MDE 142/HSS 196-grade,MDE 132/TUR 102-grade,CSS 312/INF 313-grade,MDE 143/HSS 295-grade,CSS 206/INF 202-grade,MDE 144/HSS 296-grade,MDE 134/TUR 214-grade,MAT 158/MAT 154-grade,HSS 222/MDE 172-grade
0,Android,71.0,75,71,61.0,77,78,75.0,97.0,92,...,98,91,58.0,70.0,93.0,83.0,92,74,63.0,77.0
1,IT Project Manager,80.0,90,92,85.0,53,52,66.0,95.0,90,...,95,91,64.0,63.0,94.0,65.0,92,70,75.0,57.0
2,Front End Developer,90.0,95,91,90.0,96,87,71.0,93.0,86,...,97,92,75.0,92.0,91.0,78.0,93,65,90.0,80.0
3,Front End Developer,90.0,84,86,90.0,84,87,55.0,100.0,90,...,100,91,75.0,62.0,94.0,73.0,92,50,82.0,62
4,IT project manager,90.0,93,96,85.0,75,80,70.0,NaN,96,...,95,93,84.0,82.0,91.0,73.0,93,66,93.0,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Configuration / QA Testing,77.0,71.0,71.0,64.0,88.0,72.0,86.0,53.0,98.0,...,95.0,95.0,88.0,91.0,95.0,83.0,95.0,89.0,88.0,89.0
196,UX/UI Designer,50.0,81.0,50.0,56.0,78.0,63.0,50.0,54.0,71.0,...,84.0,95.0,NaN,0.0,90.0,NaN,95.0,NaN,0.0,88.0
197,Data Science,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,85.0,...,95.0,95.0,NaN,80.0,100.0,94.0,87.0,NaN,73.0,95.0
199,Backend developer,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,85.0,...,95.0,95.0,NaN,80.0,100.0,94.0,87.0,NaN,73.0,95.0
200,Unity developer,68.0,53.0,70.0,60.0,59.0,68.0,74.0,NaN,81.0,...,95.0,100.0,64.0,0.0,90.0,86.0,95.0,83.0,62.0,59.0

In [8]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('filtered_final_merged_file.csv(without_credit)')

# Replace NaN values with 0
df.fillna(0, inplace=True)

# Save the modified DataFrame back to a CSV file
df.to_csv('filtered_final_merged_file.csv(without_credit,without_NaN)', index=False)
df

,IT_Experience,MAT 151-grade,MAT 153-grade,INF 106-grade,MAT 156-grade,CSS 215-grade,MAT 251-grade,CSS 220-grade,CSS 410-grade,MDE 171/HSS 111-grade,...,MDE 141/HSS 195-grade,MDE 142/HSS 196-grade,MDE 132/TUR 102-grade,CSS 312/INF 313-grade,MDE 143/HSS 295-grade,CSS 206/INF 202-grade,MDE 144/HSS 296-grade,MDE 134/TUR 214-grade,MAT 158/MAT 154-grade,HSS 222/MDE 172-grade
0,Android,71.0,75,71,61.0,77,78,75.0,97.0,92,...,98,91,58.0,70.0,93.0,83.0,92,74,63.0,77.0
1,IT Project Manager,80.0,90,92,85.0,53,52,66.0,95.0,90,...,95,91,64.0,63.0,94.0,65.0,92,70,75.0,57.0
2,Front End Developer,90.0,95,91,90.0,96,87,71.0,93.0,86,...,97,92,75.0,92.0,91.0,78.0,93,65,90.0,80.0
3,Front End Developer,90.0,84,86,90.0,84,87,55.0,100.0,90,...,100,91,75.0,62.0,94.0,73.0,92,50,82.0,62
4,IT project manager,90.0,93,96,85.0,75,80,70.0,0.0,96,...,95,93,84.0,82.0,91.0,73.0,93,66,93.0,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,UX/UI Designer,50.0,81.0,50.0,56.0,78.0,63.0,50.0,54.0,71.0,...,84.0,95.0,0.0,0.0,90.0,0.0,95.0,0,0.0,88.0
197,Data Science,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,85.0,...,95.0,95.0,0.0,80.0,100.0,94.0,87.0,0,73.0,95.0
198,ICT,0.0,0,0,0.0,0,0,0.0,0.0,77.0,...,93.0,95.0,95.0,0.0,0.0,0.0,0,0,0.0,0
199,Backend developer,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,85.0,...,95.0,95.0,0.0,80.0,100.0,94.0,87.0,0,73.0,95.0
200,Unity developer,68.0,53.0,70.0,60.0,59.0,68.0,74.0,0.0,81.0,...,95.0,100.0,64.0,0.0,90.0,86.0,95.0,83.0,62.0,59.0

In [20]:
import pandas as pd
import numpy as np

# Read the CSV file into a DataFrame
df = pd.read_csv('filtered_final_merged_file.csv(without_credit)-rows')

mat_columns = df.filter(like='MAT')

# Convert non-numeric values to NaN
mat_columns = mat_columns.apply(pd.to_numeric, errors='coerce')

# Compute the average of "MAT" columns, skipping NaN values
mat_avg = mat_columns.mean(axis=1)

# Merge "MAT" columns into a new column with the average values
df['MAT_Average'] = mat_avg

# Drop the original "MAT" columns
df.drop(columns=mat_columns.columns, inplace=True)

# Save the modified DataFrame back to a CSV file
df.to_csv('modified_file.csv', index=False)
df

,IT_Experience,INF 106-grade,CSS 215-grade,CSS 220-grade,CSS 410-grade,MDE 171/HSS 111-grade,MDE 131/TUR 101-grade,MDE 141/HSS 195-grade,MDE 142/HSS 196-grade,MDE 132/TUR 102-grade,CSS 312/INF 313-grade,MDE 143/HSS 295-grade,CSS 206/INF 202-grade,MDE 144/HSS 296-grade,MDE 134/TUR 214-grade,HSS 222/MDE 172-grade,MAT_Average
0,Android,71,77,75.0,97.0,92,57.0,98,91,58.0,70.0,93.0,83.0,92,74,77.0,69.6
1,IT Project Manager,92,53,66.0,95.0,90,86.0,95,91,64.0,63.0,94.0,65.0,92,70,57.0,76.4
2,Front End Developer,91,96,71.0,93.0,86,90.0,97,92,75.0,92.0,91.0,78.0,93,65,80.0,90.4
3,Front End Developer,86,84,55.0,100.0,90,91.0,100,91,75.0,62.0,94.0,73.0,92,50,62,86.6
4,IT project manager,96,75,70.0,NaN,96,97.0,95,93,84.0,82.0,91.0,73.0,93,66,68,88.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,Configuration / QA Testing,71.0,88.0,86.0,53.0,98.0,96.0,95.0,95.0,88.0,91.0,95.0,83.0,95.0,89.0,89.0,74.4
185,UX/UI Designer,50.0,78.0,50.0,54.0,71.0,NaN,84.0,95.0,NaN,0.0,90.0,NaN,95.0,NaN,88.0,50.0
186,Data Science,76.0,89.0,90.0,35.0,85.0,NaN,95.0,95.0,NaN,80.0,100.0,94.0,87.0,NaN,95.0,76.0
187,Backend developer,76.0,89.0,90.0,35.0,85.0,NaN,95.0,95.0,NaN,80.0,100.0,94.0,87.0,NaN,95.0,76.0
188,Unity developer,70.0,59.0,74.0,NaN,81.0,80.0,95.0,100.0,64.0,0.0,90.0,86.0,95.0,83.0,59.0,62.2

In [21]:
import pandas as pd
import numpy as np

# Read the CSV file into a DataFrame
df = pd.read_csv('modified_file.csv')

mat_columns = df.filter(like='INF')

# Convert non-numeric values to NaN
mat_columns = mat_columns.apply(pd.to_numeric, errors='coerce')

# Compute the average of "MAT" columns, skipping NaN values
mat_avg = mat_columns.mean(axis=1)

# Merge "MAT" columns into a new column with the average values
df['INF_Average'] = mat_avg

# Drop the original "MAT" columns
df.drop(columns=mat_columns.columns, inplace=True)

# Save the modified DataFrame back to a CSV file
df.to_csv('modified_file1.csv', index=False)
df

,IT_Experience,CSS 215-grade,CSS 220-grade,CSS 410-grade,MDE 171/HSS 111-grade,MDE 131/TUR 101-grade,MDE 141/HSS 195-grade,MDE 142/HSS 196-grade,MDE 132/TUR 102-grade,MDE 143/HSS 295-grade,MDE 144/HSS 296-grade,MDE 134/TUR 214-grade,HSS 222/MDE 172-grade,MAT_Average,INF_Average
0,Android,77,75.0,97.0,92,57.0,98,91,58.0,93.0,92,74,77.0,69.6,74.666667
1,IT Project Manager,53,66.0,95.0,90,86.0,95,91,64.0,94.0,92,70,57.0,76.4,73.333333
2,Front End Developer,96,71.0,93.0,86,90.0,97,92,75.0,91.0,93,65,80.0,90.4,87.000000
3,Front End Developer,84,55.0,100.0,90,91.0,100,91,75.0,94.0,92,50,62,86.6,73.666667
4,IT project manager,75,70.0,NaN,96,97.0,95,93,84.0,91.0,93,66,68,88.2,83.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,Configuration / QA Testing,88.0,86.0,53.0,98.0,96.0,95.0,95.0,88.0,95.0,95.0,89.0,89.0,74.4,81.666667
185,UX/UI Designer,78.0,50.0,54.0,71.0,NaN,84.0,95.0,NaN,90.0,95.0,NaN,88.0,50.0,25.000000
186,Data Science,89.0,90.0,35.0,85.0,NaN,95.0,95.0,NaN,100.0,87.0,NaN,95.0,76.0,83.333333
187,Backend developer,89.0,90.0,35.0,85.0,NaN,95.0,95.0,NaN,100.0,87.0,NaN,95.0,76.0,83.333333
188,Unity developer,59.0,74.0,NaN,81.0,80.0,95.0,100.0,64.0,90.0,95.0,83.0,59.0,62.2,52.000000

In [22]:
import pandas as pd
import numpy as np

# Read the CSV file into a DataFrame
df = pd.read_csv('modified_file1.csv')

mat_columns = df.filter(like='CSS')

# Convert non-numeric values to NaN
mat_columns = mat_columns.apply(pd.to_numeric, errors='coerce')

# Compute the average of "MAT" columns, skipping NaN values
mat_avg = mat_columns.mean(axis=1)

# Merge "MAT" columns into a new column with the average values
df['CSS_Average'] = mat_avg

# Drop the original "MAT" columns
df.drop(columns=mat_columns.columns, inplace=True)

# Save the modified DataFrame back to a CSV file
df.to_csv('modified_file2.csv', index=False)
df

,IT_Experience,MDE 171/HSS 111-grade,MDE 131/TUR 101-grade,MDE 141/HSS 195-grade,MDE 142/HSS 196-grade,MDE 132/TUR 102-grade,MDE 143/HSS 295-grade,MDE 144/HSS 296-grade,MDE 134/TUR 214-grade,HSS 222/MDE 172-grade,MAT_Average,INF_Average,CSS_Average
0,Android,92,57.0,98,91,58.0,93.0,92,74,77.0,69.6,74.666667,83.000000
1,IT Project Manager,90,86.0,95,91,64.0,94.0,92,70,57.0,76.4,73.333333,71.333333
2,Front End Developer,86,90.0,97,92,75.0,91.0,93,65,80.0,90.4,87.000000,86.666667
3,Front End Developer,90,91.0,100,91,75.0,94.0,92,50,62,86.6,73.666667,79.666667
4,IT project manager,96,97.0,95,93,84.0,91.0,93,66,68,88.2,83.666667,72.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,Configuration / QA Testing,98.0,96.0,95.0,95.0,88.0,95.0,95.0,89.0,89.0,74.4,81.666667,75.666667
185,UX/UI Designer,71.0,NaN,84.0,95.0,NaN,90.0,95.0,NaN,88.0,50.0,25.000000,60.666667
186,Data Science,85.0,NaN,95.0,95.0,NaN,100.0,87.0,NaN,95.0,76.0,83.333333,71.333333
187,Backend developer,85.0,NaN,95.0,95.0,NaN,100.0,87.0,NaN,95.0,76.0,83.333333,71.333333
188,Unity developer,81.0,80.0,95.0,100.0,64.0,90.0,95.0,83.0,59.0,62.2,52.000000,66.500000

In [34]:
import pandas as pd
import numpy as np

# Read the CSV file into a DataFrame
df = pd.read_csv('filtered_final_merged_file.csv(without_credit)')

mat_columns = df.filter(like='MDE')

# Convert non-numeric values to NaN
mat_columns = mat_columns.apply(pd.to_numeric, errors='coerce')

# Compute the average of "MAT" columns, skipping NaN values
mat_avg = mat_columns.mean(axis=1)

# Merge "MAT" columns into a new column with the average values
df['MDE_Average'] = mat_avg

# Drop the original "MAT" columns
df.drop(columns=mat_columns.columns, inplace=True)

# Save the modified DataFrame back to a CSV file
df.to_csv('modified_file07.csv', index=False)
df

,IT_Experience,MAT 151-grade,MAT 153-grade,INF 106-grade,MAT 156-grade,CSS 215-grade,MAT 251-grade,CSS 220-grade,CSS 410-grade,CSS 312/INF 313-grade,CSS 206/INF 202-grade,MAT 158/MAT 154-grade,MDE_Average
0,Android,71.0,75,71,61.0,77,78,75.0,97.0,70.0,83.0,63.0,81.333333
1,IT Project Manager,80.0,90,92,85.0,53,52,66.0,95.0,63.0,65.0,75.0,82.111111
2,Front End Developer,90.0,95,91,90.0,96,87,71.0,93.0,92.0,78.0,90.0,85.444444
3,Front End Developer,90.0,84,86,90.0,84,87,55.0,100.0,62.0,73.0,82.0,82.777778
4,IT project manager,90.0,93,96,85.0,75,80,70.0,NaN,82.0,73.0,93.0,87.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,UX/UI Designer,50.0,81.0,50.0,56.0,78.0,63.0,50.0,54.0,0.0,NaN,0.0,87.166667
197,Data Science,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,80.0,94.0,73.0,92.833333
198,ICT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.400000
199,Backend developer,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,80.0,94.0,73.0,92.833333
200,Unity developer,68.0,53.0,70.0,60.0,59.0,68.0,74.0,NaN,0.0,86.0,62.0,83.000000

In [24]:
import pandas as pd
file_path = 'filtered_final_merged_file.csv(without_credit)'
data = pd.read_csv(file_path)
data

,IT_Experience,MAT 151-grade,MAT 153-grade,INF 106-grade,MAT 156-grade,CSS 215-grade,MAT 251-grade,CSS 220-grade,CSS 410-grade,MDE 171/HSS 111-grade,...,MDE 141/HSS 195-grade,MDE 142/HSS 196-grade,MDE 132/TUR 102-grade,CSS 312/INF 313-grade,MDE 143/HSS 295-grade,CSS 206/INF 202-grade,MDE 144/HSS 296-grade,MDE 134/TUR 214-grade,MAT 158/MAT 154-grade,HSS 222/MDE 172-grade
0,Android,71.0,75,71,61.0,77,78,75.0,97.0,92,...,98,91,58.0,70.0,93.0,83.0,92,74,63.0,77.0
1,IT Project Manager,80.0,90,92,85.0,53,52,66.0,95.0,90,...,95,91,64.0,63.0,94.0,65.0,92,70,75.0,57.0
2,Front End Developer,90.0,95,91,90.0,96,87,71.0,93.0,86,...,97,92,75.0,92.0,91.0,78.0,93,65,90.0,80.0
3,Front End Developer,90.0,84,86,90.0,84,87,55.0,100.0,90,...,100,91,75.0,62.0,94.0,73.0,92,50,82.0,62
4,IT project manager,90.0,93,96,85.0,75,80,70.0,NaN,96,...,95,93,84.0,82.0,91.0,73.0,93,66,93.0,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,UX/UI Designer,50.0,81.0,50.0,56.0,78.0,63.0,50.0,54.0,71.0,...,84.0,95.0,NaN,0.0,90.0,NaN,95.0,NaN,0.0,88.0
197,Data Science,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,85.0,...,95.0,95.0,NaN,80.0,100.0,94.0,87.0,NaN,73.0,95.0
198,ICT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.0,...,93.0,95.0,95.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,Backend developer,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,85.0,...,95.0,95.0,NaN,80.0,100.0,94.0,87.0,NaN,73.0,95.0
200,Unity developer,68.0,53.0,70.0,60.0,59.0,68.0,74.0,NaN,81.0,...,95.0,100.0,64.0,0.0,90.0,86.0,95.0,83.0,62.0,59.0

In [26]:
import pandas as pd
file_path = 'modified_file3.csv'
data = pd.read_csv(file_path)
data

,IT_Experience,MAT_Average,INF_Average,CSS_Average,MDE_Average
0,Android,69.6,74.666667,83.000000,81.333333
1,IT Project Manager,76.4,73.333333,71.333333,82.111111
2,Front End Developer,90.4,87.000000,86.666667,85.444444
3,Front End Developer,86.6,73.666667,79.666667,82.777778
4,IT project manager,88.2,83.666667,72.500000,87.000000
...,...,...,...,...,...
184,Configuration / QA Testing,74.4,81.666667,75.666667,93.333333
185,UX/UI Designer,50.0,25.000000,60.666667,87.166667
186,Data Science,76.0,83.333333,71.333333,92.833333
187,Backend developer,76.0,83.333333,71.333333,92.833333
188,Unity developer,62.2,52.000000,66.500000,83.000000

In [43]:
import pandas as pd
file_path = 'modified_file07.csv'
data = pd.read_csv(file_path)
data

,IT_Experience,MAT 151-grade,MAT 153-grade,INF 106-grade,MAT 156-grade,CSS 215-grade,MAT 251-grade,CSS 220-grade,CSS 410-grade,CSS 312/INF 313-grade,CSS 206/INF 202-grade,MAT 158/MAT 154-grade
0,Android,71.0,75,71,61.0,77,78,75.0,97.0,70.0,83.0,63.0
1,IT Project Manager,80.0,90,92,85.0,53,52,66.0,95.0,63.0,65.0,75.0
2,Front End Developer,90.0,95,91,90.0,96,87,71.0,93.0,92.0,78.0,90.0
3,Front End Developer,90.0,84,86,90.0,84,87,55.0,100.0,62.0,73.0,82.0
4,IT project manager,90.0,93,96,85.0,75,80,70.0,NaN,82.0,73.0,93.0
...,...,...,...,...,...,...,...,...,...,...,...,...
196,UX/UI Designer,50.0,81.0,50.0,56.0,78.0,63.0,50.0,54.0,0.0,NaN,0.0
197,Data Science,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,80.0,94.0,73.0
198,ICT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,Backend developer,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,80.0,94.0,73.0
200,Unity developer,68.0,53.0,70.0,60.0,59.0,68.0,74.0,NaN,0.0,86.0,62.0

In [35]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('modified_file3.csv')

# Filter columns that contain 'INF' in their names
inf_columns = df.filter(like='CSS')

# Print the filtered columns
print(inf_columns)

     CSS_Average
0      83.000000
1      71.333333
2      86.666667
3      79.666667
4      72.500000
..           ...
184    75.666667
185    60.666667
186    71.333333
187    71.333333
188    66.500000

[189 rows x 1 columns]

In [35]:
import pandas as pd

df = pd.read_csv('modified_file07.csv')

mde_columns = df.columns[df.columns.str.contains('MDE')]

df.drop(columns=mde_columns, inplace=True)

df.to_csv('modified_file07.csv', index=False)
df

,IT_Experience,MAT 151-grade,MAT 153-grade,INF 106-grade,MAT 156-grade,CSS 215-grade,MAT 251-grade,CSS 220-grade,CSS 410-grade,CSS 312/INF 313-grade,CSS 206/INF 202-grade,MAT 158/MAT 154-grade
0,Android,71.0,75,71,61.0,77,78,75.0,97.0,70.0,83.0,63.0
1,IT Project Manager,80.0,90,92,85.0,53,52,66.0,95.0,63.0,65.0,75.0
2,Front End Developer,90.0,95,91,90.0,96,87,71.0,93.0,92.0,78.0,90.0
3,Front End Developer,90.0,84,86,90.0,84,87,55.0,100.0,62.0,73.0,82.0
4,IT project manager,90.0,93,96,85.0,75,80,70.0,NaN,82.0,73.0,93.0
...,...,...,...,...,...,...,...,...,...,...,...,...
196,UX/UI Designer,50.0,81.0,50.0,56.0,78.0,63.0,50.0,54.0,0.0,NaN,0.0
197,Data Science,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,80.0,94.0,73.0
198,ICT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,Backend developer,82.0,70.0,76.0,65.0,89.0,90.0,90.0,35.0,80.0,94.0,73.0
200,Unity developer,68.0,53.0,70.0,60.0,59.0,68.0,74.0,NaN,0.0,86.0,62.0

In [36]:
import pandas as pd

# Create a sample dataframe
data = {'Type_of_file': ['Categorized MAT, INF, CSS, MDE subjects(modified_file01.csv)', 'Categorized MAT, INF, CSS subjects(modified_file02.csv)', 
                        'Categorized MAT, INF, CSS, MDE subjects without rows containing more than 5 NaN values(modified_file03.csv)',
                        'Categorized MAT, INF, CSS subjects without rows containing more than 5 NaN values(modified_file04.csv)',
                        'No categorization and without rows containing more than 5 NaN values(modified_file05.csv)',
                        'No categorization, no MDE and without rows containing more than 5 NaN values(modified_file06.csv)',
                        'No categorization and no MDE(modified_file07.csv)'],
        'Random Forest Classifier Accuracy': [0.6176470588235294, 0.6176470588235294, 0.53125, 0.59375, 0.53125, 0.5, 0.6176470588235294],
        'Logistic Regression Accuracy': [0.6470588235294118, 0.5588235294117647, 0.625, 0.625, 0.65625, 0.5625, 0.5294117647058824],
        'Random Forest Accuracy': [0.6176470588235294, 0.5882352941176471, 0.65625, 0.65625, 0.59375, 0.625, 0.5882352941176471],
        'Randomized Search Cross-Validation Technique Accuracy': [0.6176470588235294, 0.5882352941176471, 0.71875, 0.625, 0.5625, 0.625, 0.5],
        'Decision tree Accuracy': [0.5294117647058824, 0.5882352941176471, 0.53125, 0.59375, 0.34375, 0.40625, 0.4411764705882353]}

df = pd.DataFrame(data)

# Define the file path
file_path = 'accuracy_table.xlsx'

# Export the dataframe to Excel
df.to_excel(file_path, index=False)

print("Excel file created successfully!")
df

Excel file created successfully!

,Type_of_file,Random Forest Classifier Accuracy,Logistic Regression Accuracy,Random Forest Accuracy,Randomized Search Cross-Validation Technique Accuracy,Decision tree Accuracy
0,"Categorized MAT, INF, CSS, MDE subjects(modifi...",0.617647,0.647059,0.617647,0.617647,0.529412
1,"Categorized MAT, INF, CSS subjects(modified_fi...",0.617647,0.558824,0.588235,0.588235,0.588235
2,"Categorized MAT, INF, CSS, MDE subjects withou...",0.531250,0.625000,0.656250,0.718750,0.531250
3,"Categorized MAT, INF, CSS subjects without row...",0.593750,0.625000,0.656250,0.625000,0.593750
4,No categorization and without rows containing ...,0.531250,0.656250,0.593750,0.562500,0.343750
5,"No categorization, no MDE and without rows con...",0.500000,0.562500,0.625000,0.625000,0.406250
6,No categorization and no MDE(modified_file07.csv),0.617647,0.529412,0.588235,0.500000,0.441176